### ISSUE TITLE
cs_filter_crime - miscategorizing rape

### ISSUE THREAD

**Issue by jesnstevens** [slu-openGIS/compstatr#17]
**Describe the bug**
Hi @chris-prener - Awesome package! I noticed that the `cs_filter_crime` when the crime is "rape" is including/categorizing more than just rapes in the dataset. 

**Expected behavior**
Only Rape should be categorized as rape. 

**To Reproduce**
This doesn't occur in the Jan 2018 dataset included in the package but does when calling other months - this is why I haven't included an official reprex but I do have minimal code that should reproduce this issue. 

```r
# Load Dependencies
library(compstatr)

# Load Index & Data
i <- cs_create_index()
june2018 <- cs_get_data(year = 2018, month = "june", index = i)

# subset rapes and removed unfounded incidents
juneRapes <- cs_filter_count(june2018, var = count)
juneRapes <- cs_filter_crime(juneRapes, var = crime, crime = "rape")

# View First Part of Object
head(juneRapes)
```

**Screenshots**
![image](https://user-images.githubusercontent.com/21069023/64442583-aa74da00-d095-11e9-8738-397c5d56ef24.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 enterprise
 - Version of R: v3.5.3
 - Version of RStudio v1.1.463

**Comment by jesnstevens** [comment]
I've been doing some more digging and it looks like there are other things being miscategorized as well:

![image](https://user-images.githubusercontent.com/21069023/64446362-3854c300-d09e-11e9-8c3c-e079acb55eae.png)

**To reproduce** 
```r
# Load Dependencies
library(compstatr)

# Load Index & Data
i <- cs_create_index()
june2018 <- cs_get_data(year = 2018, month = "june", index = i)

# add Categories
june2018 <- cs_filter_count(june2018, var = count)
june2018 <- cs_crime_cat(june2018, var = crime, crimeCatNum, "numeric")
june2018 <- cs_crime_cat(june2018, var = crime, crimeCatName, "string")
```

**Comment by chris-prener** [comment]
OK - I'll have to look into what is going on! Thanks for bringing this up, @jesnstevens!  

@bransonf - take note - looks like there is a bug in here... I'll get it squashed quickly...

**Comment by chris-prener** [comment]
Hey @jesnstevens - wanted to let you know the bug is fixed. `compstatr` has an opinionated validation process that addresses, among other things, the variable types. Since you were just looking at a single month and didn't go through the validation process, `crime` remained `character` and therefore was not parsing correctly. 

This is a totally understandable approach to using the package, and I've modified both `cs_crime_cat` and `cs_filter_crime` to ensure that `crime` is `integer` before proceeding with the categorization/subsetting process.

That said, if you are going to be using this for work (and you totally should!), check out the validation process to make sure you're building accurate tables of crimes.

Your workflow should work as intended, now:

``` r
# Update package to GitHub version
remotes::install_github("slu-openGIS/compstatr")

# Load Dependencies
library(compstatr)

# Load Index & Data
i <- cs_create_index()
june2018 <- cs_get_data(year = 2018, month = "june", index = i)

# subset rapes and removed unfounded incidents
juneRapes <- cs_filter_count(june2018, var = count)
juneRapes <- cs_filter_crime(juneRapes, var = crime, crime = "rape")

# View First Part of Object
head(juneRapes)
#> # A tibble: 6 x 20
#>   complaint coded_month date_occur flag_crime flag_unfounded
#>   <chr>     <chr>       <chr>      <chr>      <chr>         
#> 1 18-027408 2018-06     01/01/201… Y          <NA>          
#> 2 18-026515 2018-06     04/01/201… Y          <NA>          
#> 3 18-024557 2018-06     04/07/201… Y          <NA>          
#> 4 18-023617 2018-06     05/23/201… Y          <NA>          
#> 5 18-026098 2018-06     05/27/201… Y          <NA>          
#> 6 18-024634 2018-06     06/01/201… Y          <NA>          
#> # … with 15 more variables: flag_administrative <chr>, count <chr>,
#> #   flag_cleanup <chr>, crime <int>, district <chr>, description <chr>,
#> #   ileads_address <chr>, ileads_street <chr>, neighborhood <chr>,
#> #   location_name <chr>, location_comment <chr>, cad_address <chr>,
#> #   cad_street <chr>, x_coord <chr>, y_coord <chr>
```

<sup>Created on 2019-09-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
