### ISSUE TITLE
too strict crs test

### ISSUE THREAD

**Issue by edzer** [slu-openGIS/compstatr#19]
While running reverse dependency checks on sf I'm now seeing this:
```
  > test_check("compstatr")
  ── 1. Failure: correct output is returned on sample data (@test_projectXY.R#36)
  sf::st_crs(results)[[1]] not equal to 4269.
  Types not compatible: character is not double
```
the structure of `crs` objects is going to change; please don't write tests at this level. Testing that `st_crs(result)$epsg == 4267)` should be enough.

**Comment by chris-prener** [comment]
Thanks @edzer - sorry for the delay - this was marked as spam by my email system. Will address this!

**Comment by edzer** [comment]
sf has now been submitted to CRAN; compstatr still gives an error.

**Comment by chris-prener** [comment]
Thanks @edzer - appreciate the reminder. Hope you're doing well with everything going on right now.

**Comment by rsbivand** [comment]
To avoid having to condition on **sf** version in the test, I suggest muting until you have time to fix it. Hard-testing output from `st_crs()` should probably be avoided - it may vary with PROJ and `proj.db` version, but a non-**testthat** base test which just diffs will not throw an error but will alert a human observer. I see that you  now access the `$epsg` of the object, but I would still advise against any tests throwing errors or warnings on CRS/crs until things calm down (1-2Q 2022 best guess).

**Comment by chris-prener** [comment]
Appreciate the guidance, @rsbivand!

**Comment by chris-prener** [comment]
Fixed with latest version
