### ISSUE TITLE
cs_validate November 2020 data

### ISSUE THREAD

**Issue by Logowilliams** [slu-openGIS/compstatr#24]
Hey Chris!

@jesnstevens  and I have been using compstatr a lot and it is an awesome tool! We ran into an issue with the November 2020 data after realizing that `cs_validate` returns `FALSE` for 2020 because of errors in the data for the month of November. More specifically, `valVars` was `FALSE` for the month of November. I tried correcting these errors using `cs_extract_month` and `cs_standardize` but neither correct the errors in the month of November. 

We thought that the error was coming from the mispelling of "y_coord" as "ycoord" in the data but after correcting for that issue it didn't seem to solve anything. As soon as we run `cs_collapse` the y values are split into two seperate columns: `y_coord` and `ycoord`. Do you have any thoughts? I've included a reprex below:

```r
library(compstatr)
#get crime data for 2020
i <- cs_create_index()
yearlist20 <- cs_get_data(year = 2020, index = i)                          
cs_validate(yearlist20, year = 2020)

#try and correct November data
cs_standardize(yearlist20, month = "November", config = 26)
nov <- cs_extract_month(yearlist20, month = "November")
nov <- rename(nov, y_coord = ycoord)
cs_replace_month(yearlist20, month = "November", nov)

ytdCrimes20 <- cs_collapse(yearlist20)
```

 - OS: macOS High Sierra 10.13.6
 - Version of R [v4.0.3]
 - Version of RStudio [v1.2.5042]

Thanks for your help!

**Comment by chris-prener** [comment]
Thanks @Logowilliams - I think the `cs_standardize()` is superfluous. Here is the code chunk I've been using successfully:

```r
# initial validate
expect_equal(cs_validate(data2020_raw, year = "2020"), FALSE)

# verbose validation
cs_validate(data2020_raw, year = "2020", verbose = TRUE)

# extract data and unit test column name
nov20 <- cs_extract_month(data2020_raw, month = "November")
expect_equal("ycoord" %in% names(nov20), TRUE)

# standardize variable names
nov20 <- rename(nov20, y_coord = ycoord)

# replace data
data2020_raw <- cs_replace_month(data2020_raw, month = "November", monthData = nov20)

# validate
expect_equal(cs_validate(data2020_raw, year = "2020"), TRUE)
```

The `expect_equal()` function is from the `testthat` package - I've been extending the logic of "unit testing" from software development to my data analysis workflows to make sure scripts error if the data don't meet certain conditions. 

Let me know if this works!

**Comment by Logowilliams** [comment]
That worked perfectly, thanks @chris-prener !

**Comment by chris-prener** [comment]
Great @Logowilliams!
